import { Injectable } from '@angular/core';


    const STAR = 'app/scrabbleImages/starTile.jpg';
    const NORMAL = 'app/scrabbleImages/ordinaryTile.jpg';
    const DOUBLE_LETTER_SCORE = 'app/scrabbleImages/doubleLetterScore.jpg';
    const DOUBLE_WORD_SCORE = 'app/scrabbleImages/doubleWordScore.jpg';
    const TRIPLE_LETTER_SCORE = 'app/scrabbleImages/tripleLetterScore.jpg';
    const TRIPLE_WORD_SCORE = 'app/scrabbleImages/tripleWordScore.jpg';

    const ROW_0 = [TRIPLE_WORD_SCORE, NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
       NORMAL, NORMAL, TRIPLE_WORD_SCORE, NORMAL, NORMAL,
       NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL, TRIPLE_WORD_SCORE];
    const ROW_1 = [NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL, NORMAL,
       TRIPLE_LETTER_SCORE, NORMAL, NORMAL, NORMAL, TRIPLE_LETTER_SCORE,
       NORMAL, NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL];
    const ROW_2 = [NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL,
       NORMAL, DOUBLE_LETTER_SCORE, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
       NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL];
    const ROW_3 = [DOUBLE_LETTER_SCORE, NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL,
       NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL,
       NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL, DOUBLE_LETTER_SCORE];
    const ROW_4 = [NORMAL, NORMAL, NORMAL, NORMAL, DOUBLE_WORD_SCORE,
       NORMAL, NORMAL, NORMAL, NORMAL, NORMAL,
       DOUBLE_WORD_SCORE, NORMAL, NORMAL, NORMAL, NORMAL];
    const ROW_5 = [NORMAL, TRIPLE_LETTER_SCORE, NORMAL, NORMAL, NORMAL,
       TRIPLE_LETTER_SCORE, NORMAL, NORMAL, NORMAL, TRIPLE_LETTER_SCORE,
       NORMAL, NORMAL, NORMAL, TRIPLE_LETTER_SCORE, NORMAL];
    const ROW_6 = [NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL,
       NORMAL, DOUBLE_LETTER_SCORE, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
       NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL];
    const ROW_7 = [TRIPLE_WORD_SCORE, NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
       NORMAL, NORMAL, STAR, NORMAL, NORMAL,
       NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL, TRIPLE_WORD_SCORE];
    const ROW_8 = [NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL,
       NORMAL, DOUBLE_LETTER_SCORE, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
       NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL];
    const ROW_9 = [NORMAL, TRIPLE_LETTER_SCORE, NORMAL, NORMAL, NORMAL,
        TRIPLE_LETTER_SCORE, NORMAL, NORMAL, NORMAL, TRIPLE_LETTER_SCORE,
        NORMAL, NORMAL, NORMAL, TRIPLE_LETTER_SCORE, NORMAL];
    const ROW_10 = [NORMAL, NORMAL, NORMAL, NORMAL, DOUBLE_WORD_SCORE,
        NORMAL, NORMAL, NORMAL, NORMAL, NORMAL,
        DOUBLE_WORD_SCORE, NORMAL, NORMAL, TRIPLE_LETTER_SCORE, NORMAL];
    const ROW_11 = [DOUBLE_LETTER_SCORE, NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL,
        NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL,
        NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL, DOUBLE_LETTER_SCORE];
    const ROW_12 = [NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL,
        NORMAL, DOUBLE_LETTER_SCORE, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
        NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL];
    const ROW_13 = [NORMAL, DOUBLE_WORD_SCORE, NORMAL, NORMAL, NORMAL,
        TRIPLE_LETTER_SCORE, NORMAL, NORMAL, NORMAL, TRIPLE_LETTER_SCORE,
        NORMAL, NORMAL, NORMAL, DOUBLE_WORD_SCORE, NORMAL];
    const ROW_14 = [TRIPLE_WORD_SCORE, NORMAL, NORMAL, DOUBLE_LETTER_SCORE, NORMAL,
        NORMAL, NORMAL, TRIPLE_WORD_SCORE, NORMAL, NORMAL,
        NORMAL, DOUBLE_LETTER_SCORE, NORMAL, NORMAL, TRIPLE_WORD_SCORE];

@Injectable()
export class ScrabbleBoardService {

    private _scrabbleGrid : string[][];

    constructor() {
        this._scrabbleGrid = [ROW_0, ROW_1, ROW_2, ROW_3, ROW_4, ROW_5,
                              ROW_6, ROW_7, ROW_8, ROW_9, ROW_10,
                              ROW_11, ROW_12, ROW_13, ROW_14];
    }
    getScrabbleGrid(): string[][] {
        return this._scrabbleGrid;
    }
}
